"""确定性的 Next.js 14 (App Router) + Tailwind 脚手架。

样板文件不变、不需要 LLM（规则引擎能做的不用 LLM）。Builder 只生成特性文件，
write_app() 把脚手架与特性文件合并写盘（特性文件可覆盖同名脚手架文件）。
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Dict, List, Optional

from .schemas import GeneratedFile
from .util import npm_package_name, resolve_within

_PACKAGE_JSON = """{
  "name": "__PROJECT__",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "next": "14.2.5",
    "react": "^18.3.1",
    "react-dom": "^18.3.1"
  },
  "devDependencies": {
    "typescript": "^5.4.5",
    "@types/node": "^20.14.2",
    "@types/react": "^18.3.3",
    "@types/react-dom": "^18.3.0",
    "tailwindcss": "^3.4.4",
    "postcss": "^8.4.38",
    "autoprefixer": "^10.4.19"
  }
}
"""

_NEXT_CONFIG = """/** @type {import('next').NextConfig} */
const nextConfig = {};
export default nextConfig;
"""

_TSCONFIG = """{
  "compilerOptions": {
    "target": "ES2017",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{ "name": "next" }],
    "paths": { "@/*": ["./*"] }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
"""

_POSTCSS = """export default {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};
"""

_TAILWIND = """import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: { extend: {} },
  plugins: [],
};
export default config;
"""

_GLOBALS_CSS = """@tailwind base;
@tailwind components;
@tailwind utilities;
"""

_LAYOUT = """import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "__PROJECT__",
  description: "Generated by One-Person Company AI Factory (v1)",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="zh">
      <body>{children}</body>
    </html>
  );
}
"""

_GITIGNORE = """node_modules
.next
out
"""

_ENV_LOCAL_EXAMPLE = """# Supabase（可选）：填入后生成的 app 真连 Supabase；留空则降级为本地 mock/localStorage。
NEXT_PUBLIC_SUPABASE_URL=
NEXT_PUBLIC_SUPABASE_ANON_KEY=
"""


def scaffold_files(project: str, extra_deps: Optional[Dict[str, str]] = None) -> Dict[str, str]:
    extra_deps = extra_deps or {}
    pkg = json.loads(_PACKAGE_JSON.replace("__PROJECT__", npm_package_name(project)))
    pkg["dependencies"].update(extra_deps)  # 合并白名单额外依赖
    files = {
        "package.json": json.dumps(pkg, indent=2) + "\n",
        "next.config.mjs": _NEXT_CONFIG,
        "tsconfig.json": _TSCONFIG,
        "postcss.config.mjs": _POSTCSS,
        "tailwind.config.ts": _TAILWIND,
        "app/globals.css": _GLOBALS_CSS,
        "app/layout.tsx": _LAYOUT.replace("__PROJECT__", project),
        ".gitignore": _GITIGNORE,
    }
    if "@supabase/supabase-js" in extra_deps:
        files[".env.local.example"] = _ENV_LOCAL_EXAMPLE
    return files


def write_app(
    target: Path,
    project: str,
    feature_files: List[GeneratedFile],
    extra_deps: Optional[Dict[str, str]] = None,
) -> List[Path]:
    """写脚手架 + 特性文件到 target/。特性文件覆盖同名脚手架文件。"""
    files: Dict[str, str] = scaffold_files(project, extra_deps)
    for f in feature_files:
        files[f.path] = f.content

    # Validate every untrusted path before the first write to avoid partial output.
    resolved_files = [(resolve_within(target, rel), content) for rel, content in files.items()]
    written: List[Path] = []
    for p, content in resolved_files:
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(content, encoding="utf-8")
        written.append(p)
    return written
