"""确定性的 Next.js 14 (App Router) + Tailwind 脚手架。

样板文件不变、不需要 LLM（规则引擎能做的不用 LLM）。Builder 只生成特性文件，
write_app() 把脚手架与特性文件合并写盘（特性文件可覆盖同名脚手架文件）。
"""
from __future__ import annotations

from pathlib import Path
from typing import Dict, List

from .schemas import GeneratedFile

_PACKAGE_JSON = """{
  "name": "__PROJECT__",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "next": "14.2.5",
    "react": "^18.3.1",
    "react-dom": "^18.3.1"
  },
  "devDependencies": {
    "typescript": "^5.4.5",
    "@types/node": "^20.14.2",
    "@types/react": "^18.3.3",
    "@types/react-dom": "^18.3.0",
    "tailwindcss": "^3.4.4",
    "postcss": "^8.4.38",
    "autoprefixer": "^10.4.19"
  }
}
"""

_NEXT_CONFIG = """/** @type {import('next').NextConfig} */
const nextConfig = {};
export default nextConfig;
"""

_TSCONFIG = """{
  "compilerOptions": {
    "target": "ES2017",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{ "name": "next" }],
    "paths": { "@/*": ["./*"] }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
"""

_POSTCSS = """export default {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};
"""

_TAILWIND = """import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: { extend: {} },
  plugins: [],
};
export default config;
"""

_GLOBALS_CSS = """@tailwind base;
@tailwind components;
@tailwind utilities;
"""

_LAYOUT = """import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "__PROJECT__",
  description: "Generated by One-Person Company AI Factory (v1)",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="zh">
      <body>{children}</body>
    </html>
  );
}
"""

_GITIGNORE = """node_modules
.next
out
"""


def scaffold_files(project: str) -> Dict[str, str]:
    return {
        "package.json": _PACKAGE_JSON.replace("__PROJECT__", project),
        "next.config.mjs": _NEXT_CONFIG,
        "tsconfig.json": _TSCONFIG,
        "postcss.config.mjs": _POSTCSS,
        "tailwind.config.ts": _TAILWIND,
        "app/globals.css": _GLOBALS_CSS,
        "app/layout.tsx": _LAYOUT.replace("__PROJECT__", project),
        ".gitignore": _GITIGNORE,
    }


def write_app(target: Path, project: str, feature_files: List[GeneratedFile]) -> List[Path]:
    """写脚手架 + 特性文件到 target/。特性文件覆盖同名脚手架文件。"""
    files: Dict[str, str] = scaffold_files(project)
    for f in feature_files:
        files[f.path.replace("\\", "/")] = f.content

    written: List[Path] = []
    for rel, content in files.items():
        p = target / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(content, encoding="utf-8")
        written.append(p)
    return written
